server:
  port: 10002

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
        - id: lock-core
          uri: lb://lock-core
          predicates:
            - Path=/lock-stock/**
          filters:
            - StripPrefix=1
#        - id: orderServiceRouter
#          uri: lb://consul-order
#          predicates:
#            - Path=/order-service/**
#          filters:
#            - StripPrefix=1
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: service-gateway

eureka:
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

  # ??????????EurekaServer???true
  client:
    register-with-eureka: true
    # ???EurekaServer?????????????true???????????????true????ribbon??????
    fetchRegistry: true
    # ????
    service-url:
      defaultZone: http://lock-eureka:8761/eureka/
  # ????
  #eureka.client.service-url.defaultZone=http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  #eureka.instance.instance-id=${spring.application.name}:${server.port}
#  # ????????IP??
#  eureka.instance.prefer-ip-address=true
#  #Eureka?????????????????????(???30?)
#  eureka.instance.lease-renewal-interval-in-seconds=1
#  #Eureka????????????????????????(???90?)????????
#  eureka.instance.lease-expiration-duration-in-seconds=2